### ISSUE TITLE
Use a class instead of a global Camomile object

### ISSUE THREAD

**Issue by rom1504** [camomile-project/camomile-client-javascript#8]
I think it would be better and would be closer to the python API https://github.com/camomile-project/camomile-client-python/blob/master/camomile/client.py#L149

Something like `var client = new Camomile('http://camomile.fr/api');`

**Comment by hbredin** [comment]
Yes. Definitely. Feel free to contribute this change!

**Comment by hbredin** [comment]
Even better if multiple clients can be instantiated at once. This could allow two things:
* log in with 2 different users (e.g. one with and one without admin privileges)
* log in to 2 different servers (e.g. to transfer annotations from one server to another).

**Comment by rom1504** [comment]
Ok I'm doing that.
I'm wondering if I can use ES6 ? It has a better syntax for classes.
There are 2 possibilities to use es6 : 
* add transpilers tools in the project (babel) : keep retrocompatibility with old browsers versions that don't support es6. But it means `npm install` will take a bit more time (for devs, not for users)
* just not support older browsers : are users using older browsers ?

**Comment by hbredin** [comment]
I don't mind getting rid of old browsers.

**Comment by rom1504** [comment]
done by #9
